print('Chamamos as funções pelo nome seguido de parenteses com ou sem argumentos.')
print('a função type(42) retornará o tipo do parâmetro passado.')
print(type(42))
print()

print('Outro exemplo é a função int() que retornará o valor inteito relativo a um parâmetro.')
print('int ("32") retornará:')
print(int("32"))
print('int (3.27) retornará:')
print(int(3.27))
print('Também temos o float retorna o ponto flutuante referente a um parâmetro.')
print('por exemplo, float(32) retornará:')
print(float(32))
print("float('3.14') retornará:")
print(float('3.14'))
print('Por fim temos o str() trazendo o parâmetro passado em formato de string.')
print("um str(32) então retorna:")
print(str(32))
